# change the following lines in a new installation:
# - ports on host if needed


version: '3'
  
services:
  # Database
  database:
    image: mariadb:10
    volumes:
    - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: lamp-db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: asdf
    restart: always
  
  #phpmyadmin
  phpmyadmin:
    depends_on:
     - database
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: toor
      PMA_HOST: database:3306
    restart: always

  #php + Apache
  php:
    image: trrtle/php_apache:1.0
    ports:
     - 80:80
    volumes: 
      - ./var/www:/var/www
    restart: always

volumes:
  mariadb:
    

